import { ACADEMICSTATE, DEGREE, GENDER, REGISTERSTATUS, ROLES, SEMESTERTYPE } from "./types";

export const dataPeriod = [
  {
    id: "1",
    year: 2024,
    semester_type: SEMESTERTYPE.GANJIL,
    academic_state: ACADEMICSTATE.CLOSE,
    created_at: new Date(2024, 6, 10, 0, 0, 0),
    updated_at: new Date(2024, 6, 10, 0, 0, 0),
  },
  {
    id: "2",
    year: 2025,
    semester_type: SEMESTERTYPE.GENAP,
    academic_state: ACADEMICSTATE.CLOSE,
    created_at: new Date(2025, 0, 10, 0, 0, 0),
    updated_at: new Date(2025, 0, 10, 0, 0, 0),
  },
  {
    id: "3",
    year: 2025,
    semester_type: SEMESTERTYPE.GANJIL,
    academic_state: ACADEMICSTATE.ONGOING,
    created_at: new Date(2025, 6, 10, 0, 0, 0),
    updated_at: new Date(2025, 6, 10, 0, 0, 0),
  },
  {
    id: "4",
    year: 2026,
    semester_type: SEMESTERTYPE.GENAP,
    academic_state: ACADEMICSTATE.PLANNING,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
];

export const dataMajor = [
  {
    id: "1",
    code: "SI",
    name: "Sistem Informasi",
    degree: DEGREE.S1,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
  {
    id: "2",
    code: "TI",
    name: "Teknik Informatika",
    degree: DEGREE.S1,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
];

export const dataOperator = [
  {
    id: "1",
    name: 'alex',
    employee_id: '12345678',
    department: 'Prodi',
    role: ROLES.ADMIN,
    userId: "admin1",
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
  {
    id: "2",
    name: 'Kaza Orenda',
    employee_id: '123456438',
    department: 'Keuangan',
    role: ROLES.FINANCE,
    userId: "finance1",
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
  {
    id: "3",
    name: 'Hira Amalia',
    employee_id: '123458587',
    department: 'Akademik',
    role: ROLES.BAAK,
    userId: "baak1",
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
  },
];

export const dataLecturer = [
  {
    id: "1",
    name: "Sapere aude, M.Kom",
    employee_id: '098.1235.123',
    gender: GENDER.PRIA,
    degree: DEGREE.S2,
    entryYear: '2008',
    email: undefined,
    phone: undefined,
    avatar: undefined,
    majorId: '1',
    major: {
      id: "1",
      code: "SI",
      name: "Sistem Informasi",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    role: ROLES.LECTURER,
    userId: 'lecturer1',
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "2",
    name: "Chasiah Mikami, M.Kom, PhD",
    employee_id: '098.1244.124',
    gender: GENDER.WANITA,
    degree: DEGREE.S3,
    entryYear: '2007',
    email: undefined,
    phone: undefined,
    avatar: undefined,
    majorId: '2',
    major: {
      id: "2",
      code: "TI",
      name: "Teknik Informatika",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    role: ROLES.ADVISOR,
    userId: 'advisor1',
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
];

export const dataStudent = [
  {
    id: "1",
    name: "Hayami Liora",
    nim: "310126012001",
    gender: GENDER.WANITA,
    entryYear: "2026",
    register_status: REGISTERSTATUS.NEW,
    place_of_birth: "Banjarmasin",
    birthday: new Date(2007, 3, 11, 0, 0, 0),
    email: "",
    phone: "",
    avatar: "",
    majorId: "1",
    major: {
      id: "1",
      code: "SI",
      name: "Sistem Informasi",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    role: "STUDENT" as ROLES,
    userId: "student1",
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "2",
    name: "Sundreesoro Migiora",
    nim: "310126022001",
    gender: GENDER.PRIA,
    entryYear: "2026",
    register_status: REGISTERSTATUS.NEW,
    place_of_birth: "Banjarmasin",
    birthday: new Date(2007, 3, 11, 0, 0, 0),
    email: "",
    phone: "",
    avatar: "",
    majorId: "2",
    major: {
      id: "2",
      code: "TI",
      name: "Teknik Informatika",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    role: "STUDENT" as ROLES,
    userId: "student2",
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
];

export const dataComponent = [
  {
    id: "1",
    name: "Absensi",
    description: "Absensi ",
    acronym: 'Abs',
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "2",
    name: "Tugas Mandiri",
    description: undefined,
    acronym: 'Mandiri',
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "3",
    name: "Ujian Akhir Semester",
    description: undefined,
    acronym: 'UTS',
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
];

export const dataCourseType = [
  {
    id: 1,
    name: 'Wajib',
    description: undefined,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: 2,
    name: 'Pilihan',
    description: undefined,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
];

export const dataAssessmentModel = [
  {
    id: "1",
    name: "REGULER",
    description: undefined,
    assessmentModelComponent: [
      {
        id: 'assscomp1',
        assessmentModelId: '1',
        assessmentComponentId: "1",
        assessmentComponent: {
          id: "1",
          name: "Absensi",
          description: "Absensi ",
          acronym: 'Abs',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 10,
        sort_order: 1,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
      {
        id: 'assscomp2',
        assessmentModelId: '1',
        assessmentComponentId: '2',
        assessmentComponent: {
          id: '2',
          name: "Tugas Mandiri",
          description: undefined,
          acronym: 'Mandiri',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 25,
        sort_order: 2,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
      {
        id: 'assscomp3',
        assessmentModelId: '1',
        assessmentComponentId: '3',
        assessmentComponent: {
          id: '3',
          name: "Ujian Akhir Semester",
          description: undefined,
          acronym: 'UTS',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 50,
        sort_order: 3,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
    ],
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "2",
    name: "CASE METHOD",
    description: undefined,
    assessmentModelComponent: [
      {
        id: 'assscomp4',
        assessmentModelId: '2',
        assessmentComponentId: '1',
        assessmentComponent: {
          id: '1',
          name: "Absensi",
          description: "Absensi ",
          acronym: 'Abs',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 15,
        sort_order: 1,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
      {
        id: 'assscomp5',
        assessmentModelId: '2',
        assessmentComponentId: '2',
        assessmentComponent: {
          id: '2',
          name: "Tugas Mandiri",
          description: undefined,
          acronym: 'Mandiri',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 42,
        sort_order: 2,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
      {
        id: 'assscomp6',
        assessmentModelId: '2',
        assessmentComponentId: '3',
        assessmentComponent: {
          id: '3',
          name: "Ujian Akhir Semester",
          description: undefined,
          acronym: 'UTS',
          created_at: new Date(2026, 0, 10, 0, 0, 0),
          updated_at: new Date(2026, 0, 10, 0, 0, 0),
          deleted_at: undefined,
        },
        percentage: 43,
        sort_order: 3,
        created_at: new Date(2026, 0, 10, 0, 0, 0),
        updated_at: new Date(2026, 0, 10, 0, 0, 0),
        deleted_at: undefined,
      },
    ],
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
]

export const dataCourse = [
  {
    id: "1",
    code: "SB-ISI-006",
    name: "Bahasa Indonesia",
    credit: 3,
    majorId: "1",
    major: {
      id: "1",
      code: "SI",
      name: "Sistem Informasi",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    assessmentModelId: "1",
    courseTypeId: 1,
    courseType: {
      id: 1,
      name: 'Wajib',
      description: undefined,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
      deleted_at: undefined,
    },
    validFrom: new Date(2026, 0, 10, 0, 0, 0),
    validTo: undefined,
    predecessorId: undefined,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
  {
    id: "2",
    code: "SB-ITI-017",
    name: "Matematika",
    credit: 3,
    majorId: "2",
    major: {
      id: "2",
      code: "TI",
      name: "Teknik Informatika",
      degree: DEGREE.S1,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
    },
    assessmentModelId: "1",
    courseTypeId: 1,
    courseType: {
      id: 1,
      name: 'Wajib',
      description: undefined,
      created_at: new Date(2026, 0, 10, 0, 0, 0),
      updated_at: new Date(2026, 0, 10, 0, 0, 0),
      deleted_at: undefined,
    },
    validFrom: new Date(2026, 0, 10, 0, 0, 0),
    validTo: undefined,
    predecessorId: undefined,
    created_at: new Date(2026, 0, 10, 0, 0, 0),
    updated_at: new Date(2026, 0, 10, 0, 0, 0),
    deleted_at: undefined,
  },
]